# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted  
    env:
      DOTNET_INSTALL_DIR: "./.dotnet"
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.100-preview.7.24407.12
    - name: Install .NET Wasm Tools
      run: dotnet workload install wasm-tools
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build
    - name: Publish
      run: dotnet publish /home/thnak/git-actions/actions-runner/my-home-center-work/CodeWithMe/CodeWithMe/WebApp/WebApp/WebApp.csproj --runtime linux-x64 --self-contained true
    - name: Test
      run: dotnet test --no-build --verbosity normal
